### ISSUE TITLE
(Weird Issue) Using shaders causes you to be able to see through most blocks.  1.18 0.60-alpha.8.1

### ISSUE THREAD

**Issue by Kakiharu** [BiggerSeries/Phosphophyllite#10]
I was testing shaders out in a modpack and went through 130 mods only to find out this api combined with "All the Tweaks" was causing the issues. I'm on the forge 38.0.17 Minecraft 1.18 using the Optifine with any Shader. Discovered issue on All the Mods 7 but can recreate with just Phos , All the Tweaks and Optifine. Both mods alone do not create this issue.

**Comment by RogueLogix** [comment]
As long as this doesn't show up without optifire, i dont care.
Optifire fucks with so many things its not even funny, and i directly use OpenGL and custom shaders, so they aren't even remotely compatible nor will ever be.

**Comment by GordonHollow** [comment]
So you just tell people don't play with shaders?

If i should choose beaytiful lighting and shadows from shaders or just one reactors mod - it's obvious =)

Cause there is no other ways to play with shaders on forge, rather than Optifine...

**Comment by RogueLogix** [comment]
Yes. The fact that Optifine is broken is not my problem.

**Comment by GordonHollow** [comment]
Don't need Optifine themselves, but play without shaders is ugly for me...

**Comment by RogueLogix** [comment]
That's, also, not my problem. 

I mimic the visuals of the vanilla shaders, as that is the only constant I can rely on. Even if I wanted to support optifine/shaders (which i dont) the shader pack dev would need to create special shaders for my pipeline, which works completely different from how vanilla's does and also doesnt pass around the info that optifine shaders need to work properly anyway, so it wouldn't work regardless.

**Comment by GordonHollow** [comment]
Just create issue on Optifine github, maybe they fix this problem from their side
