### ISSUE TITLE
Crash on start [1.18.1]

### ISSUE THREAD

**Issue by red2blue** [BiggerSeries/Phosphophyllite#12]
https://pastebin.com/SX4ANjX5

**Comment by gizmocodes** [comment]
Currently there is an issue with Quartz (part of Phosphophyllite) that issues that error message when another mod fails to load (which creates a red herring). Could you please post the full log file so we can examine that as well? This might be similar to #11.

**Comment by gizmocodes** [comment]
Closing due to lack of response, if the fix mentioned in that issue isn't the cause and the next update (whenever it's pushed) doesn't fix it, then please reopen this issue again.
