### ISSUE TITLE
Crash on 1.18.1 Forge

### ISSUE THREAD

**Issue by SebVFX** [BiggerSeries/Phosphophyllite#13]
Hey :)

Minecraft crashes immediately after start.
I did read the issue a user submitted before but I was not able to respond, so i hope it's ok to open a new one with the crash report you asked for.

Crash Report:

> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 19.12.21, 20:02
> Description: Quartz failed to startup
> 
> java.lang.IllegalAccessError: class net.roguelogix.phosphophyllite.quartz.internal.common.B3DStateHelper tried to access private field com.mojang.blaze3d.vertex.BufferUploader.f_166831_ (net.roguelogix.phosphophyllite.quartz.internal.common.B3DStateHelper is in module phosphophyllite@0.6.0-alpha.9.1 of loader 'TRANSFORMER' @15d42ccb; com.mojang.blaze3d.vertex.BufferUploader is in module minecraft@1.18.1 of loader 'TRANSFORMER' @15d42ccb)
> 	at net.roguelogix.phosphophyllite.quartz.internal.common.B3DStateHelper.bindArrayBuffer(B3DStateHelper.java:18) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLBuffer.<init>(GLBuffer.java:175) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLCore.allocBuffer(GLCore.java:123) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLCore.allocBuffer(GLCore.java:31) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.QuartzCore.<init>(QuartzCore.java:95) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:mixin,re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLCore.<init>(GLCore.java:33) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLCore.attemptCreate(GLCore.java:70) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.gl.GLCore.<clinit>(GLCore.java:38) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.QuartzCore.createCore(QuartzCore.java:47) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:mixin,re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.QuartzCore.createCore(QuartzCore.java:53) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:mixin,re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.QuartzCore.<clinit>(QuartzCore.java:36) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:mixin,re:classloading}
> 	at net.roguelogix.phosphophyllite.quartz.internal.EventListener.<clinit>(EventListener.java:28) ~[phosphophyllite-1.18.1-0.6.0-alpha.9.1.jar%2383!:0.6.0-alpha.9.1] {re:mixin,re:classloading}
> 	at com.mojang.blaze3d.platform.Window.handler$zbe000$startQuartz(Window.java:746) ~[client-1.18.1-20211210.034407-srg.jar%23100!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:phosphophyllite.mixins.json:QuartzStartupMixin,pl:mixin:A}
> 	at com.mojang.blaze3d.platform.Window.<init>(Window.java:148) ~[client-1.18.1-20211210.034407-srg.jar%23100!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:phosphophyllite.mixins.json:QuartzStartupMixin,pl:mixin:A}
> 	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23100!:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[client-1.18.1-20211210.034407-srg.jar%23100!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphophyllite.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.1-20211210.034407-srg.jar%23100!:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.5.jar%2323!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.18.1
> 	Minecraft Version ID: 1.18.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 1869578560 bytes (1782 MiB) / 3355443200 bytes (3200 MiB) up to 8589934592 bytes (8192 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
> 	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
> 	Microarchitecture: Zen
> 	Frequency (GHz): 3,19
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095,00
> 	Graphics card #0 deviceId: 0x1c03
> 	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
> 	Memory slot #0 capacity (MB): 8192,00
> 	Memory slot #0 clockSpeed (GHz): 2,40
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192,00
> 	Memory slot #1 clockSpeed (GHz): 2,40
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 19392,81
> 	Virtual memory used (MB): 13642,25
> 	Swap memory total (MB): 3072,00
> 	Swap memory used (MB): 183,40
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=21M
> 	OptiFine Version: OptiFine_1.18.1_HD_U_H4
> 	OptiFine Build: 20211212-175054
> 	Render Distance Chunks: 12
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: null
> 	OpenGlRenderer: null
> 	OpenGlVendor: null
> 	CpuCount: 12

Thank you very much in advance!

**Comment by RogueLogix** [comment]
I have an access transformer in place to allow me to access that, so, this shouldn't be possible.
Can you provide your mod-list?

**Comment by SebVFX** [comment]
Yeah of course! I am sorry that it took 3 days to respond to your question! Was a bit busy short before christmas.

![Screenshot 2021-12-22 223837](https://user-images.githubusercontent.com/10141948/147158194-28bd56e0-6af6-4533-9aca-271ca4ac5d24.png)

![Screenshot 2021-12-22 224156](https://user-images.githubusercontent.com/10141948/147158508-4eb345ff-8b89-4cba-bc77-7e4b91032534.png)

![Screenshot 2021-12-22 224212](https://user-images.githubusercontent.com/10141948/147158518-d5ec042b-d365-4c30-a934-2f15adca8a44.png)

I wish you very happy christmas days in advance!

**Comment by gizmocodes** [comment]
Could you please try without Optifine to see if the crash still persists?

**Comment by AlienXAXS** [comment]
Hi, I ran into the same problem with attempting to add additional mods to ATM7.
The mod in question for me that brought the same stack trace was the following: StylishEffects-v3.0.1-1.18.1-Forge.jar

I am unsure if this is a change in your code base, or a change in theirs, but I thought I would mention it.

**Comment by MrBackups** [comment]
Hi All, I had the same crash today when trying to start up, but I was on Forge 39.0.6, and no optifine.  I updated to the newer forge 39.0.8 and it started right up.  Hope this might help.

**Comment by SebVFX** [comment]
Hey! I updated to forge 39.0.8 today and it seems to work perfectly fine now, also with optifine enabled.
Thanks for your help all :)

@gizmocodes I did try without optifine before but that did not change anything.

**Comment by RogueLogix** [comment]
if its working now, im going to close this issue
