### ISSUE TITLE
[Bug] Quartz failed to startup - java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Ridanisaurus** [BiggerSeries/Phosphophyllite#15]
Game fails to start when both `Phosphophyllite` and `Functional Storage` are used in the same modpack.

Forge Version: 1.18.1-39.0.8
Mod Version:
- Phosphophyllite: phosphophyllite-1.18.1-0.6.0-alpha.9.1
- Functional Storage: functionalstorage-1.18.1-0.0.1

Crash Log:
https://gist.github.com/Ridanisaurus/cb509073e800283865249d434a70e774

**Comment by ModernGamingWorld** [comment]
Any update on a fix for this as, Functional storage will keep crashing

**Comment by Ridanisaurus** [comment]
It seems that the initial version of Functional Storage had an issue with its dependency on Titanium. Luckily, the later versions of Functional Storage auto-download Titanium, which fixes this issue.

**Comment by Ridanisaurus** [comment]
> Any update on a fix for this as, Functional storage will keep crashing

Just update to the latest version of Functional Storage

**Comment by RogueLogix** [comment]
related, this type of phosphophyllite crash was fixed in these commits https://github.com/BiggerSeries/Phosphophyllite/commit/a4afc9c066beb07a012b04e0c1879e77c5915f74 https://github.com/BiggerSeries/Phosphophyllite/commit/8162ac7a52b24e2ea248b01f8b4fda8db4e83f36
