### ISSUE TITLE
Description: Rendering overlay  java.lang.IllegalStateException: Failed to load shader code for phosphophyllite:quartz/shaders/gl/main

### ISSUE THREAD

**Issue by MrBackups** [BiggerSeries/Phosphophyllite#16]
Minecraft crashing at startup.  Removed all resource packs, and I don't have any shaders installed.

Description: Rendering overlay
Forge Version: 1.18.1-39.0.9
Mod Version:  Phosphophyllite: phosphophyllite-1.18.1-0.6.0-alpha.9.1

[crash-2021-12-29_11.32.09-client.txt](https://github.com/BiggerSeries/Phosphophyllite/files/7789836/crash-2021-12-29_11.32.09-client.txt)
.

**Comment by RogueLogix** [comment]
full log plz

**Comment by MrBackups** [comment]
Here is what I found in the logs folder and crash-reports folder for the last attempt to load.  Let me know if you are looking for something different.  Thank you!

[crash-2021-12-29_11.53.38-client.txt](https://github.com/BiggerSeries/Phosphophyllite/files/7790507/crash-2021-12-29_11.53.38-client.txt)
[latest.log](https://github.com/BiggerSeries/Phosphophyllite/files/7790515/latest.log)

**Comment by RogueLogix** [comment]
actual error happened earlier, rsinfinitybooster is the mod at fault here
```
[11:53:19] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid rsinfinitybooster
java.lang.NoSuchFieldError: MAIN_GROUP
	at uk.co.hexeption.rsinfinitybooster.item.DimensionCard.<init>(DimensionCard.java:15) ~[RSInfinityBooster-1.18.1-2.0+5.jar%23195!:1.18.1-2.0+5]```

**Comment by MrBackups** [comment]
Yep, removed that and it seems to have fixed me.  Thanks!!

**Comment by RogueLogix** [comment]
related, this crash mode was fixed in https://github.com/BiggerSeries/Phosphophyllite/commit/8162ac7a52b24e2ea248b01f8b4fda8db4e83f36
