### ISSUE TITLE
NBT Crash with latest build for 1.19.2.

### ISSUE THREAD

**Issue by seancrain** [BiggerSeries/Phosphophyllite#26]
https://www.nosiphus.com/minecraft/crash-reports/crash-2022-12-16_17.21.16-server.txt

Upon updating to 1.19.2-0.6.0-beta.6.2, this error is preventing the server from starting.

**Comment by RogueLogix** [comment]
once its done, try this build, https://github.com/BiggerSeries/Phosphophyllite/actions/runs/3717324488

**Comment by seancrain** [comment]
That fixed the crash, can this hotfix be uploaded to CurseForge ASAP?

**Comment by RogueLogix** [comment]
Yes, just wanted to make sure that fixed it
