### ISSUE TITLE
The error says to add to config, but it does not work

### ISSUE THREAD

**Issue by TechniumUnlimited** [BiggerSeries/Phosphophyllite#3]
Failure message: Phosphophyllite (phosphophyllite) has failed to load correctly
		java.lang.IllegalStateException: Performant is incompatible with Phosphophyllite
		This is a known issue with performant and it breaking other mods, the author does not care
		GitHub issue on the matter: https://github.com/someaddons/performant_issues/issues/70
		To bypass this check add "bypassPerformantCheck: true" to your phosphophyllite config
		If you bypass this check I (RogueLogix) will not provide any support for any issues related to Phosphophyllite or the mods that use it
		If you believe your issue is unrelated, disabled performant and reproduce it
		By choosing to bypass this check you understand that here there be dragons

The config does not look like it will accept just that at the end of the file....

**Comment by TechniumUnlimited** [comment]
As adding that line will not be json...
```
{
    GUI: {
        /* 
         * Valid range: [50,)
         * Default: 200
         */
        UpdateIntervalMS: 200.0,

    },

}

**Comment by RogueLogix** [comment]
outer/first json scope

**Comment by TechniumUnlimited** [comment]
Like this? 
```
{
	bypassPerformantCheck: true,
    GUI: {
        /* 
         * Valid range: [50,)
         * Default: 200
         */
        UpdateIntervalMS: 200.0,

    },

}

**Comment by TechniumUnlimited** [comment]
Sir I dont understand what I do

**Comment by RogueLogix** [comment]
That will work, *however* I recommend you heed the warning and just remove performant. It doesn't actually make anything run faster. What it does amounts to faking the tick number, breaking other mods in the process.
