### ISSUE TITLE
java.lang.IllegalStateException: Performant is incompatible with Phosphophyllite

### ISSUE THREAD

**Issue by lipa0drk** [BiggerSeries/Phosphophyllite#7]
This is a known issue with performant and it breaking other mods, the author does not care

i cant start my personal modpack idk whats the problem

**Comment by gizmocodes** [comment]
The modpack you're using includes both BiggerReactors/Phosphophyllite, and the Performant mod (as mentioned in the issue). Performant breaks a lot of mods, including Phosphophyllite, so an error check was added to check for Performant on launch. Either remove Performant, or enable the hidden config option to bypass this check (if you do this config bypass, then we, the developers, will provide _no_ support for the mod; check the log file for instructions on how to do this).
